### ISSUE TITLE
Retry Processor failing with php-amqplib

### ISSUE THREAD

**Issue by jean-gui** [swarrot/swarrot#101]
Hi,

When I use Swarrot (v2.0.2) (or rather SwarrotBundle (dev-master), but I believe the problem is in Swarrot) with the retry processor, I get the following error when that processor tries to republish a message to the retry exchange:
```
  [PhpAmqpLib\Exception\AMQPProtocolChannelException]                                      
  PRECONDITION_FAILED - user_id property set to '0' but authenticated user was '******'  
```
I think the problem may have been introduced by https://github.com/swarrot/swarrot/pull/62 as it is setting default values conflicting with the way amqplib (v2.5.1) works.
Fixing the problem might be as easy as setting keys only for properties that actually have a value. 

If it makes sense, I can try to submit a PR.

**Comment by odolbeau** [comment]
Hi!
There is sibling problem with pecl but on (very) old versions of RabbitMQ only.
I think your bug is linked to #62 & #81.

Of course you can submit a PR. :)
