### ISSUE TITLE
the retry processor fails saying that the processing mode is unknown

### ISSUE THREAD

**Issue by stof** [swarrot/swarrot#103]
When queueing a message for retry, the processor fails:

```
Server channel error: 406, message: PRECONDITION_FAILED - invalid message: {delivery_mode_unknown,0}
```

I'm using the pecl extension with ext-amqp 1.6.0beta2 (compiled against librabbitmq 0.5.2) and RabbitMQ 3.4.2

**Comment by stof** [comment]
It seems like ``AMQPEnvelope#getDeliveryMode()`` returns 0

**Comment by odolbeau** [comment]
I really to test this but I lake of time. :/
I hope I will be able to take a look at this next week.
Maybe it's due to default parameters a bit like #101 ?
Did you tried to comment [this line](https://github.com/swarrot/swarrot/blob/master/src/Swarrot/Broker/MessageProvider/PeclPackageMessageProvider.php#L39) maybe?

**Comment by stof** [comment]
Well, if we omit this, publishing the retry will work again because it will use the default values when publishing. But the published message will not be persistent, which would also be a bug (though less critical than the current one).
It looks like a bug in the extension though, as I don't see why ``getDeliveryMode`` should return ``0``.

Btw, can you reopen this issue ? I don't think closing it makes sense.

**Comment by odolbeau** [comment]
Sorry, I pushed the wrong button! Oo

**Comment by L0rD59** [comment]
Hi guys,

Same issue here,

like @odolbeau say, if we comment [this line](https://github.com/swarrot/swarrot/blob/master/src/Swarrot/Broker/MessageProvider/PeclPackageMessageProvider.php#L39) that's work.

I use RabbitMQ 3.5.3

**Comment by L0rD59** [comment]
Hi,

some news, i tried with these bellow configuration : 
rabbitmq-c 0.5.2 / pecl amqp-1.4.0
rabbitmq-c 0.5.2 / pecl amqp-1.6.0beta2
rabbitmq-c 0.5.2 / pecl amqp-1.6.0beta3

rabbitmq-c 0.6.0 / pecl amqp-1.6.0beta2
rabbitmq-c 0.6.0 / pecl amqp-1.6.0beta3

i've got same error but through exception

[AMQPQueueException]                                                                                  
  Server channel error: 406, message: PRECONDITION_FAILED - invalid message: {delivery_mode_unknown,0}

**Comment by stof** [comment]
@L0rD59 I was also getting it through an exception. I posted the exception message
