### ISSUE TITLE
How to set options to a processor?

### ISSUE THREAD

**Issue by zspine** [swarrot/swarrot#145]
I've been trying to understand how the option part of the swarrot library works, but still couldn't find any good examples or documentations :(

if you take MaxMessagesProcessor for example, how do we properly set the 'max_messages' value to the stack? Is it possible to set it through a final processor?

**Comment by zspine** [comment]
I have finally figured out...

```
class TestProcessor implements ConfigurableInterface
{
    public function process(Message $message, array $options)
    {
        echo sprintf("Message body #%s\n", $message->getBody());
    }

    public function setDefaultOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('max_messages', 1);
    }
}
```

**Comment by odolbeau** [comment]
That's it. :)
