### ISSUE TITLE
MaxMessagesProcessor with supervisor

### ISSUE THREAD

**Issue by zspine** [swarrot/swarrot#146]
processors used:
Swarrot\Processor\MaxMessages\MaxMessagesProcessor
Swarrot\Processor\SignalHandler\SignalHandlerProcessor
Swarrot\Processor\Ack\AckProcessor

I have configured a consumer to consume 500 messages at a time and to exit and then to start a new process with supervisor. But it seems signals are not properly working and after the first run script exits with an error and supervisor status displays it as 'Exited too quickly (process log may have details)'.

Anything missing here?
```
[program:php-app-1]
command=/opt/rh/rh-php56/root/usr/bin/php /home/webmaster/app/app.php
autostart=true
autorestart=true
startretries=3
stderr_logfile=/home/webmaster/app/app.err.log
stdout_logfile=/home/webmaster/app/app.out.log
user=www-data
process_name=%(program_name)s
numprocs=1
```

Thank you!

**Comment by stof** [comment]
well, if your message processing triggers some error, it would stop the process immediately here (and probably do it in a loop as the message would stay the first one in the queue), as you don't have the ExceptionCatcherProcessor in your stack. May it be your issue ?

**Comment by zspine** [comment]
Hi @stof 

Thank you very much for the quick response. I forgot to mention that the script is running fine without 'MaxMessagesProcessor' limit and no exception thrown.

Finally I found the actual cause for the error, if a process exits within 1 sec then supervisor assumes it as a failure. We can change this configuration..

`startsecs=0`

FYI: https://github.com/Supervisor/supervisor/issues/212

Thanks again for your help and support!
