### ISSUE TITLE
Add support for blocking queue consuming

### ISSUE THREAD

**Issue by NoiseByNorthwest** [swarrot/swarrot#150]
Hi,

As I have mentioned earlier in #106, I have a big problem with the current Consumer implementation which is based on a busy wait loop with a configurable sleep duration (aka poll interval).
More precisely:
- With high poll interval: we lose message processing responsiveness and capacity to throttle under heavy load.
- With low poll interval: we waste CPU time which is a big problem, at least for polar bears.

So are you ok if I PR the following changes ?
- add a "BlockingMessageProviderInterface" with consume(callable $consumer, int $timeout) as single method
- make PeclPackageMessageProvider an implementation of BlockingMessageProviderInterface
- handle the case "$this->messageProvider instanceof BlockingMessageProviderInterface" in Consumer::consume() to take advantage of blocking API

**Comment by odolbeau** [comment]
Hi,

With a high poll interval, you may have to wait a bit before starting consuming messages but is it really a problem? Even if the poll interval is, let's say 500000 microseconds (500ms), do you really need to avoid this delay when consuming the first message, even if you're under heavy load?

As explained in the first comment on [PHP.net](http://php.net/manual/en/function.usleep.php):
> the idea of sleep and usleep is that by letting the cpu run a few idle cycles so the other programs can have some cycles run of their own.
Which means we don't waste CPU time at all.

Furthermore, regarding [the extension implementation](https://github.com/pdezwart/php-amqp/blob/master/amqp_queue.c#L568-L569), it looks like the timeout must be in seconds. Even if you set a timeout of 1 second, that's very high.

At the end:
* if you're under heavy load, you don't have any sleep, all messages are consumed as soon as the previous one is consumed.
* if your queue is empty, you won't waste a lot of CPU time.

IMO, it's up to you to choose a `poll_interval` which fit your needs. The default one may be a bit low if you don't have a lot of messages to consume.

**Comment by NoiseByNorthwest** [comment]
Thanks for your reply.

> With a high poll interval, you may have to wait a bit before starting consuming messages but is it really a problem? Even if the poll interval is, let's say 500000 microseconds (500ms), do you really need to avoid this delay when consuming the first message, even if you're under heavy load?

OK, I've just missed the nested while here:
https://github.com/swarrot/swarrot/blob/master/src/Swarrot/Consumer.php#L79

Got it.

> Furthermore, regarding the extension implementation, it looks like the timeout must be in seconds. Even if you set a timeout of 1 second, that's very high.

In fact the code you are linking just tells read_timeout is a double property of AMQPConnection properly translated to a struct timeval value with its microsec part.
And it is not a problem to have a ten seconds order of magnitude read timeout. You are not supposed to quit after SIGINT/SIGTERM within a defined delay. This is more a matter of IPC convention (e.g. supervisord will kill -9 you after 30 sec.).

Finally this issue can be closed, the tradeoff with high poll interval / worst case delay for first message seems to meet my requirements.
