### ISSUE TITLE
Bump php minimal version

### ISSUE THREAD

**Issue by odolbeau** [swarrot/swarrot#152]
The php 5.4 version is not supported anymore and php 5.6 only receive security patch.

Shouldn't we bump the minimal php version to php7.0?

**Comment by Taluu** [comment]
Because a reaction is not enough : 👍 👍 👍

**Comment by olaurendeau** [comment]
Indeed 7.1 make more sense :)

**Comment by remyLemeunier** [comment]
Why not 5.6, as a lot of users are still with this version?

**Comment by odolbeau** [comment]
1/3 of packagist users use php5.6: https://seld.be/
I guess it could be a good first step but it won't let us remove all small hacks we have in both swarrot / SwarrotBundle.

**Comment by krichprollsch** [comment]
We currently still using php5.6 in our production env with Swarrot, but I agree to bump to 7.1.
As said @seldaek:

> I would like to encourage everyone to be a bit more aggressive in bumping PHP requirements when tagging new major releases of their libs. Don't forget that the old code does not go away, it's still there to be used by people using legacy PHP versions.
