### ISSUE TITLE
Support for x-delayed-message?

### ISSUE THREAD

**Issue by zspine** [swarrot/swarrot#168]
Really sorry if this looks like a support request..... but I am not sure where to post it!

1. Is it possible to use "x-delayed-message" exchange option with swarrot?
2. Retry Processor can be used for the same purpose but is there any time limit (for example delay 16 hours ?) also if we use it along with MaxExecutionTimeProcessor I believe it wont work....

**Comment by odolbeau** [comment]
Hi @zspine!

1. Yes it's possible. You can easily create a new message with specific headers like `x-delayed-message` or anything else.

2. You can have more information regarding the RetryProcessor [here](https://github.com/swarrot/swarrot/tree/master/src/Swarrot/Processor/Retry). The processor itself don't deal with time limit, only with retry attempt. You'll ave to configure your broker with the correct configuration. You might be interested by [odolbeau/rabbit-mq-admin-toolkit](https://github.com/odolbeau/rabbit-mq-admin-toolkit) which deal with this configuration.
The `MaxExecutionTimeProcessor` is not linked to the `RetryProcessor`. It will simply stop your worker after a given time. The goal is to avoid any memory leak with complex applications. You can use something like [supervisord](http://supervisord.org/) to handle your consumer (scale up/down, relaunch when stopped, etc.).

**Comment by zspine** [comment]
Hi Olivier,

Thanks a lot for the quick response... :)

1. That's great news
2. Thanks again for explaining it in detail, now I understand the difference.

Yes application (sms gateway) is bit complex and using swarrot to handle webhook delivery, so stability is pretty important.

https://github.com/odolbeau/rabbit-mq-admin-toolkit
Excellent tool :) simplifies lots of things!

Cheers!

**Comment by makasim** [comment]
Message delaying is supported internally by [interop publisher](https://github.com/swarrot/swarrot/blob/master/src/Swarrot/Broker/MessagePublisher/InteropMessagePublisher.php) as well as priorities and expiration. There are two strategies available for AMQP: dead-letter-exchange + ttl and delayed plugin based one. 

Though it is not clear how to pass all of them from outside to the publisher.
