### ISSUE TITLE
Reconfigure Packagist auto-update

### ISSUE THREAD

**Issue by stof** [swarrot/swarrot#179]
Currently, swarrot packages are updated on Packagist using the old github services integration, which is deprecated by Github and will be removed on January 31st, 2019.

Packagist now has a Github integration using Github Apps (i.e. the new way). We need to migrate to it.

@odolbeau we will need you to follow the instructions in https://packagist.org/about#how-to-update-packages (in the Github Hook section) to migrate your Packagist account. I already migrated mine, but it did not allowed migrating the swarrot packages because I only have write access on the swarrot repos, and managing hooks requires admin access.

**Comment by stof** [comment]
another question is whether @swarrot/maintainers should have admin access on the repos (but then, we still need @odolbeau to migrate the Packagist account for some other packages he owns anyway, for instance https://packagist.org/packages/odolbeau/rabbit-mq-admin-toolkit)

**Comment by odolbeau** [comment]
Thanks for this warning, it should be OK now. :+1: 

@olaurendeau & you are now owners of the swarrot organization. :)

Regarding this toolkit, do you think it's a good idea to migrate it in the swarrot organization?
Which only implies (if I'm not wrong):
* clone the package in the swarrot organization
* update composer.json to change the package name
* deprecate the old one on packagist
* (optional) Change the namespace used in the package and release a new major version

**Comment by stof** [comment]
@odolbeau not sure about that. Swarrot is specifically not restricted to AMQP (and this is why it does not have anything related to the configuration of the broker itself)
