### ISSUE TITLE
Avoid dynamic messages when logging

### ISSUE THREAD

**Issue by greg0ire** [swarrot/swarrot#187]
Right now, when I look at my Kibana dashboard, I get no grouping for some messages:

![kibana](https://user-images.githubusercontent.com/657779/57868007-77ff5280-7802-11e9-900e-b3d28a644af9.png)

This can easily be fixed by using static messages and a dynamic `$context`:

```php
    $this->logger->info(
        "[Ack] A message has been correctly ack'ed",
        [
           'message_id' => $message->getId(),
           'swarrot_processor' => 'ack',
        ]
    );
```

instead of https://github.com/swarrot/swarrot/blob/4b945ad0225a1be8e275ee83849482f3a39f33b3/src/Swarrot/Processor/Ack/AckProcessor.php#L51-L56

If you agree, I can create a PR. There are many more instances of that issue, that's why I'm asking before fixing them all.

**Comment by odolbeau** [comment]
I see no reason to have this information directly in the log message as it's not really relevant anyway.
Feel free to create the PR you described. :)
