### ISSUE TITLE
[Question] Reason for RPC processors deprecation and removal

### ISSUE THREAD

**Issue by koutsoumposval** [swarrot/swarrot#218]
Hi, 

I want to ask if there any reason other than removing the outdated dependencies, that the RPC processors were deprecated and removed?

I am thinking of using an RpcServer-like processor.

PS: I've seen the comments on this PR: https://github.com/swarrot/swarrot/pull/197/files

Thanks in advance,
Val

**Comment by odolbeau** [comment]
Hi!
As explained in [this comment](https://github.com/swarrot/swarrot/pull/197#issuecomment-557801650) & the following one, it looks like using RPC with Swarrot is not a very good idea.
TBH I never tried it, you could ask @Taluu for more information if you want.

Of course you can still retrieve those processors from the git repository & use them directly in your app or in a dedicated git repository if you want. :)

Don't hesitate if you have another question.

**Comment by koutsoumposval** [comment]
Thanks for the answer @odolbeau! 
If @Taluu knows something more I would be happy to hear :)
