### ISSUE TITLE
Question about SQSMessageProvider Deprecation

### ISSUE THREAD

**Issue by xleliberty** [swarrot/swarrot#219]
Hi, 
I've searched in issues but didn't found a thread discussing about the motivation behind deprecating SQSMessageProvider ?

Is it a lack of use cases ? or an implementation problem ? 
thanks for your answer

**Comment by odolbeau** [comment]
Hi @xleliberty 
It was mainly a lack of maintenance. almost nobody was using this provider... :(

If you're not using swarrot (yet!), I strongly recommend you to take a look at Symfony Messenger which support SQS & propose a very clean architecture! :ok_hand:

**Comment by xleliberty** [comment]
Hi Olivier, thanks for you answer.
Well, our stack is mainly based on swarrot and swarrot-bundle since years now and we where ones of the few using this implementation.
Never mind, for now i've included those classes in our tree.

And yes we are considering replacing all current messaging stack with messenger. 

Regards
